#!/usr/bin/env bash
# PreToolUse | Edit|Write|NotebookEdit
# Blocks edits to generated sources. Exit 2 blocks the call and returns stderr
# to the model, so each message names the generator that owns the file.
set -uo pipefail

p=$(jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
[ -n "$p" ] || exit 0

case "$p" in
  */scala-native-gdextension/src/main/scala/gdext/classes/*)
    echo "BLOCKED: gdext.classes is GENERATED (~1025 files). Edit the generator instead: language-binding-scala/modules/interface-generator (EngineClassGenerator.scala), then: cd language-binding-scala && sbt igen/regenerate" >&2
    exit 2 ;;
  */scala-native-gdextension/src/main/scala/gdext/internal/ffi/*)
    echo "BLOCKED: gdext.internal.ffi is GENERATED. Edit the generator instead: language-binding-scala/modules/interface-generator (InterfaceGenerator.scala), then: cd language-binding-scala && sbt igen/regenerate" >&2
    exit 2 ;;
  */godot/scala.gdextension)
    echo "BLOCKED: scala.gdextension is GENERATED by the sbt plugin (godotManifest task). Change the plugin settings instead: godotLibName / godotCompatibilityMinimum / godotManifestName." >&2
    exit 2 ;;
esac

exit 0
