
package godot.gdextensioninterface.codegen.types

import scala.scalanative.unsafe.*
import scala.scalanative.unsigned.*


object GDExtensionClassMethodArgumentMetadata {
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE: CUnsignedInt = 0.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT8: CUnsignedInt = 1.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT16: CUnsignedInt = 2.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT32: CUnsignedInt = 3.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64: CUnsignedInt = 4.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT8: CUnsignedInt = 5.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT16: CUnsignedInt = 6.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT32: CUnsignedInt = 7.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT64: CUnsignedInt = 8.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_FLOAT: CUnsignedInt = 9.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_DOUBLE: CUnsignedInt = 10.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR16: CUnsignedInt = 11.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR32: CUnsignedInt = 12.toUInt
  final val GDEXTENSION_METHOD_ARGUMENT_METADATA_OBJECT_IS_REQUIRED: CUnsignedInt = 13.toUInt
}
