extends SceneTree

# Headless validation that EVERY generated Harness node type is a real,
# instantiable Godot class with the correct base, and that a scene containing
# one of each loads. Data-driven from harness_manifest.json (generated by
# HarnessClassGenerator). Prints a summary and exits non-zero on any failure.
#
# Run: godot --headless --path . --script node_harness_verify.gd

var _failures = []

func _fail(msg) -> void:
	_failures.append(msg)

func _initialize() -> void:
	var log_file = FileAccess.open("godot-init", FileAccess.READ_WRITE)
	if log_file != null:
		log_file.seek_end()

	var manifest = _load_manifest()
	if manifest == null:
		_done(log_file, 0, 0)
		return

	var checked = 0
	for entry in manifest:
		checked += 1
		var name = entry["name"]
		var base = entry["base"]

		if not ClassDB.class_exists(name):
			_fail("%s: class does not exist" % name)
			continue
		var parent = ClassDB.get_parent_class(name)
		if parent != base:
			_fail("%s: parent is '%s', expected '%s'" % [name, parent, base])
		if not ClassDB.can_instantiate(name):
			_fail("%s: cannot instantiate" % name)
			continue
		var inst = ClassDB.instantiate(name)
		if inst == null:
			_fail("%s: instantiate() returned null" % name)
			continue
		if inst.get_class() != name:
			_fail("%s: get_class() = '%s'" % [name, inst.get_class()])
		if not inst.is_class(base):
			_fail("%s: is_class('%s') = false" % [name, base])
		inst.free()

	# Spot-check that method emission landed (inherited engine methods present
	# on the Harness subclasses via ClassDB).
	_check_method("HarnessNode2D", "set_position")
	_check_method("HarnessNode", "get_child_count")
	_check_method("HarnessNode3D", "set_position")
	_check_method("HarnessControl", "set_size")

	# Whole-scene check: every Harness node lives together in one scene.
	_check_scene(manifest.size())

	_done(log_file, checked, manifest.size())

func _load_manifest():
	var f = FileAccess.open("res://harness_manifest.json", FileAccess.READ)
	if f == null:
		_fail("could not open res://harness_manifest.json")
		return null
	var parsed = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_ARRAY:
		_fail("harness_manifest.json is not a JSON array")
		return null
	return parsed

func _check_method(cls, method) -> void:
	if ClassDB.class_exists(cls) and not ClassDB.class_has_method(cls, method):
		_fail("%s: expected inherited method '%s' missing" % [cls, method])

func _check_scene(expected) -> void:
	var packed = load("res://node_harness.tscn")
	if packed == null:
		_fail("could not load res://node_harness.tscn")
		return
	var root = packed.instantiate()
	if root == null:
		_fail("node_harness.tscn instantiate() returned null")
		return
	var count = root.get_child_count()
	if count != expected:
		_fail("scene child count = %d, expected %d" % [count, expected])
	for child in root.get_children():
		if not ClassDB.class_exists(child.get_class()):
			_fail("scene child '%s' has unknown class" % child.name)
	root.free()

func _done(log_file, checked, total) -> void:
	var ok = _failures.is_empty()
	var summary = "HARNESS VALIDATION: %s (%d/%d classes ok, %d failures)" % [
		"PASS" if ok else "FAIL", checked - _failures.size(), total, _failures.size()
	]
	print(summary)
	if log_file != null:
		log_file.store_line(summary)
	for msg in _failures:
		print("  FAIL: ", msg)
		if log_file != null:
			log_file.store_line("  FAIL: " + msg)
	if log_file != null:
		log_file.close()
	quit(0 if ok else 1)
